databases:
  - name: librarydb
    databaseName: librarydb
    user: libraryuser

services:
  - type: web
    name: library-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi_production:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: librarydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_production
      - key: WEB_CONCURRENCY
        value: 4